### ISSUE TITLE
Dockerize the Application

### ISSUE THREAD

**Issue by haseebzaki-07** [PranavBarthwal/backend-generator-cli#19]
A Dockerfile simplifies deployment by packaging a full stack app, including all dependencies, into a consistent environment, ensuring smooth operation across different systems. It also streamlines testing, scaling, and collaboration, enabling easy setup and maintenance through containerization.

**Comment by PranavBarthwal** [comment]
Hi @haseebzaki-07, thanks for creating this issue.
What's the need of docker in this application. end users are gonna interact using npm only.

**Comment by haseebzaki-07** [comment]
Docker lets u build the image of the application inside docker container using a single command and then another command will let you run the image on the ports specified on the local machine.  

This helps in avoiding installation of dependencies that comes when someone does "npm install" and also helps in Fast deployment, ease of creating new instances, and faster migrations. Ease of moving and maintaining your applications. Better security, less access needed to work with the code running inside containers, and fewer software dependencies.
