### ISSUE TITLE
stats,pricing in navbar are moved aside

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [PranavBarthwal/backend-generator-cli#22]
stats,pricing in navbar are moved aside
<img width="937" alt="image" src="https://github.com/user-attachments/assets/016b0d4f-aa46-4482-afae-e6d38be53a48">
i would like to work on it

**Comment by PranavBarthwal** [comment]
This is issue is part of another repository. You can raise the issue there.

https://github.com/PranavBarthwal/Backend-Generator-CLI-Web
