### ISSUE TITLE
adding scroll-to-top/back-to-top feature

### ISSUE THREAD

**Issue by AswaniBolisetti** [PranavBarthwal/backend-generator-cli#27]
@PranavBarthwal I would like to add the scroll-to-top feature, could you please assign me this under gssoc-ext, hacktoberfest-accepted. Could you please consider it as level2
Please give me a chance to contribute

**Comment by PranavBarthwal** [comment]
Hey @AswaniBolisetti, thanks for creating this issue, you can raise issues related to the landing page of the npm tool here: https://github.com/PranavBarthwal/Backend-Generator-CLI-Web/issues
