### ISSUE TITLE
implementing smooth scroll to navbar items

### ISSUE THREAD

**Issue by AswaniBolisetti** [PranavBarthwal/backend-generator-cli#28]
@PranavBarthwal I would like to implement a smooth scroll to the items in the navbar, could you please assign me this issue under gssoc-ext, hacktoberfest-accepted, level

**Comment by PranavBarthwal** [comment]
Hey @AswaniBolisetti, thanks for creating this issue, you can raise issues related to the landing page of the npm tool here: https://github.com/PranavBarthwal/Backend-Generator-CLI-Web/issues
