### ISSUE TITLE
Adding New Template: Rate Limiting Middleware

### ISSUE THREAD

**Issue by Amit-10101** [PranavBarthwal/backend-generator-cli#30]
**Description:**
Suggestion of adding a template for rate limiting middleware, which will limit the number of request to the application from a particular IP for preventing backend to be overwhelmed with the unnecessary frequent requests. This will improve application responsible, scalable and prevent from DDoS attacks. 

If you find this functionality good, kindly add 'gssoc-ext', 'hacktoberfest-accepted' as well as suitable level labels and assign this issue to me. 🙂

**Comment by PranavBarthwal** [comment]
go ahead, and dont forget to update the documentation with this snippet.
