### ISSUE TITLE
UPDATE contribution.md

### ISSUE THREAD

**Issue by a-n-u-vanguri** [PranavBarthwal/backend-generator-cli#42]
The contribution.md looks empty and not in a structured manner. I can update it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute. Please can you assign me this task?

Screenshots or Examples (if applicable)

No response

Checklist

- [ ] - I have checked the existing issues.
- [ ] - I have read the Contributing Guidelines.
- [ ] - I have read the Code Of Conduct.
- [ ] - The changes doesn't break the code.

**Comment by PranavBarthwal** [comment]
go ahead, assigned
