### ISSUE TITLE
Custom Project Templates for Effortless Backend Scaffolding

### ISSUE THREAD

**Issue by 0xPratikPatil** [PranavBarthwal/backend-generator-cli#6]
**Description:**

A new feature should be added to the Backend Generator CLI that allows users to create and use customizable project templates. This will give developers more flexibility when scaffolding backend projects and enable them to tailor the structure and code to meet their specific project needs.

**Feature Details:**

1. **Template Creation:**

-  Allow users to define custom project templates by specifying their own folder structure, files, and boilerplate code.

-  The CLI should accept a path to a template configuration file (e.g., JSON or YAML format) that defines these custom templates.

2. **Template Storage:**
- Implement a way to store and manage multiple custom templates locally or from a remote repository (e.g., GitHub).
Add support for syncing and downloading templates directly via the CLI.

3. **Command Addition:**
- Introduce a new command, such as `run --template <template-name>`, to generate a project using the specified custom template.

4. **Built-in Templates:**
- Provide a few pre-built customizable templates for common backend stacks (e.g., Express.js, Fastify, Nest.js) as examples for users.

Could you please assign this issue to me under GSSOC'24 extd?

**Comment by PranavBarthwal** [comment]
Great issue, Go ahead.
