### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by kartikey369-ind** [PranavBarthwal/backend-generator-cli#8]
i want to work on this please add gssoc extd and hacktoberfest lable

**Comment by PranavBarthwal** [comment]
instead of this you can add contributing guide.

**Comment by kartikey369-ind** [comment]
ok sure shall i raise other issue or edit this?

**Comment by kartikey369-ind** [comment]
done https://github.com/PranavBarthwal/backend-generator-cli/pull/10
